name: Setup Go
description: This action sets up a go environment.

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        cache: false
        go-version-file: 'go.mod'
        check-latest: true
